# Site Settings
title: CyberAdvisor
description: >-
  Cybersecurity blog, research, and projects.
baseurl: "" # Only needed if deploying under a subpath
url: "https://johnseanson.github.io" # Your GitHub Pages URL

# Author Info
author:
  show_title: false
  avatar: "/assets/images/logo.png"
  bio: "Cybersecurity analyst focused on threat intel, pen testing, and secure infrastructure."
  location: "United States"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JohnSeanson"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:Sjohnsonalpha@outlook.com"

# Theme and Appearance
remote_theme: null
minimal_mistakes_skin: "neon"

# Site Features
search: true
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
permalink: /:categories/:title/
timezone: America/Chicago
css:
  - /assets/css/custom.css


# Pages
include:
  - _pages

defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      css: "/assets/css/custom.css"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JohnSeanson"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
