title: CyberAdvisor
description: Cybersecurity blog, research, and projects.
baseurl: ""
url: "https://johnseanson.github.io"


author_profile: true
author:
  name: "Sean Johnson"
  avatar: "/assets/images/logo.png"
  bio: "Cybersecurity analyst focused on threat intel, pen testing, and secure infrastructure."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JohnSeanson"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:Sjohnsonalpha@outlook.com"



remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"

search: true
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
permalink: /:categories/:title/
timezone: America/Chicago

css:
  - /assets/css/custom.css

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      css: "/assets/css/custom.css"
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      header:
        overlay: true
        show_overlay_excerpt: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JohnSeanson"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
